import path from "node:path";
import { pathToFileURL } from "node:url";
import { chromium } from "playwright";
import { utils as xlsxUtils, write } from "xlsx";
import { backendRoot } from "../config/paths.js";

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function cleanText(value = "") {
  return String(value).replace(/\s+/g, " ").trim();
}

function normalizeCell(cell) {
  if (cell && typeof cell === "object") {
    return {
      text: cleanText(cell.text ?? cell.value ?? ""),
      header: Boolean(cell.header),
      align: cell.align || (cell.className?.includes?.("text-right") ? "right" : "left"),
      colSpan: Number(cell.colSpan || 1),
    };
  }

  return {
    text: cleanText(cell ?? ""),
    header: false,
    align: "left",
    colSpan: 1,
  };
}

function normalizeTables(tables = []) {
  return tables
    .map((table) => ({
      title: cleanText(table.title || ""),
      rows: Array.isArray(table.rows)
        ? table.rows.map((row) => row.map(normalizeCell).filter((cell) => cell.text))
        : [],
    }))
    .filter((table) => table.rows.length);
}

function tableToRows(table) {
  const rows = [];
  for (const row of table.rows) {
    rows.push(row.map((cell) => cell.text));
  }
  return rows;
}

function buildReportHtml({ title, subtitle, generatedAt, tables }) {
  const fontCss = pathToFileURL(path.join(backendRoot, "node_modules", "@fontsource", "noto-sans-bengali", "index.css")).href;
  const body = tables.map((table) => `
    ${table.title ? `<h2 style="margin:0 0 10px;font-size:18px;color:#373373;">${escapeHtml(table.title)}</h2>` : ""}
    <table width="100%" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-size:13px;margin-top:14px;">
      ${table.rows.map((row, rowIndex) => {
        const hasHeader = row.some((cell) => cell.header) || rowIndex === 0;
        return `<tr style="${hasHeader ? "background:#f4f4f4;border-top:2px solid #333;border-bottom:2px solid #333;font-weight:bold;" : "border-bottom:1px solid #eee;"}">
          ${row.map((cell) => {
            const tag = hasHeader ? "th" : "td";
            return `<${tag} colspan="${cell.colSpan}" style="padding:8px 6px;text-align:${cell.align};vertical-align:top;">${escapeHtml(cell.text)}</${tag}>`;
          }).join("")}
        </tr>`;
      }).join("")}
    </table>
  `).join("");

  return `
    <!doctype html>
    <html>
      <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="${fontCss}">
        <style>
          @page { size: A4; margin: 10mm; }
          body {
            margin: 0;
            padding: 22px;
            background: #f2f2f2;
            font-family: "Noto Sans Bengali", "Noto Sans", Arial, Helvetica, sans-serif;
            color: #1f2937;
          }
          .page {
            width: 100%;
            max-width: 900px;
            margin: 0 auto;
            background: #fff;
            border: 1px solid #ddd;
          }
        </style>
      </head>
      <body>
        <table class="page" cellpadding="0" cellspacing="0">
          <tr><td style="padding:24px;">
            <table width="100%"><tr>
              <td>
                <table><tr>
                  <td><div style="width:60px;height:60px;background:#373373;color:#fff;font-size:28px;font-weight:bold;text-align:center;line-height:60px;border-radius:8px;">SL</div></td>
                  <td style="padding-left:12px;">
                    <div style="font-size:30px;font-weight:bold;color:#373373;">StockLedger</div>
                    <div style="font-size:13px;color:#666;">Smart Inventory | POS | Accounting</div>
                    <div style="font-size:12px;color:#999;">Dhaka, Bangladesh<br>support@stockledger.app | www.stockledger.app</div>
                  </td>
                </tr></table>
              </td>
              <td align="right">
                <div style="font-size:28px;font-weight:bold;color:#373373;text-transform:uppercase;">${escapeHtml(title)}</div>
                ${subtitle ? `<div style="font-size:14px;color:#666;">${escapeHtml(subtitle)}</div>` : ""}
                <div style="font-size:12px;color:#999;">Generated: ${escapeHtml(generatedAt)}</div>
              </td>
            </tr></table>
          </td></tr>
          <tr><td style="height:4px;background:#373373;"></td></tr>
          <tr><td style="padding:20px;">${body || '<p style="font-size:13px;color:#666;">No rows available for this report.</p>'}</td></tr>
          <tr><td style="background:#fafafa;border-top:1px solid #ddd;padding:18px;">
            <table width="100%"><tr>
              <td style="font-size:12px;color:#666;">Generated by <b style="color:#373373;">StockLedger</b><br>Smart Inventory | POS | Accounting</td>
              <td align="right" style="font-size:12px;color:#666;">www.stockledger.app<br>support@stockledger.app</td>
            </tr></table>
          </td></tr>
        </table>
      </body>
    </html>
  `;
}

export class ReportExportService {
  async createPdfBuffer(payload = {}) {
    const tables = normalizeTables(payload.tables);
    const generatedAt = new Date().toLocaleString();
    const html = buildReportHtml({
      title: cleanText(payload.title || payload.fileName || "Report"),
      subtitle: cleanText(payload.subtitle || ""),
      generatedAt,
      tables,
    });

    const browser = await chromium.launch({ headless: true, args: ["--no-sandbox", "--disable-dev-shm-usage"] });
    try {
      const page = await browser.newPage({ viewport: { width: 1280, height: 1600 } });
      await page.setContent(html, { waitUntil: "networkidle" });
      await page.emulateMedia({ media: "screen" });
      await page.evaluate(() => document.fonts.ready);
      return await page.pdf({
        format: "A4",
        printBackground: true,
        preferCSSPageSize: true,
        margin: { top: "10mm", right: "10mm", bottom: "10mm", left: "10mm" },
      });
    } finally {
      await browser.close();
    }
  }

  async createExcelBuffer(payload = {}) {
    const tables = normalizeTables(payload.tables);
    const rows = [];
    tables.forEach((table, tableIndex) => {
      if (table.title) {
        rows.push([table.title]);
      }
      tableToRows(table).forEach((row) => rows.push(row));
      if (tableIndex < tables.length - 1) {
        rows.push([]);
      }
    });

    const worksheet = xlsxUtils.aoa_to_sheet(rows.length ? rows : [["No rows available"]]);
    const workbook = xlsxUtils.book_new();
    xlsxUtils.book_append_sheet(workbook, worksheet, cleanText(payload.sheetName || payload.title || "Report").slice(0, 31));
    return write(workbook, { bookType: "xlsx", type: "buffer" });
  }
}
