// Resolves a Tailwind color shade to a CSS variable holding "R G B" channels,
// so opacity modifiers (e.g. border-slate-200/70) keep working via rgb(... / alpha).
function withOpacity(variableName) {
  return ({ opacityValue }) =>
    opacityValue === undefined ? `rgb(var(${variableName}))` : `rgb(var(${variableName}) / ${opacityValue})`;
}

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Segoe UI Variable', 'Segoe UI', 'Avenir Next', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        soft: '0 20px 50px rgba(15, 23, 42, 0.08)',
      },
      colors: {
        slate: {
          50: withOpacity('--slate-50'),
          100: withOpacity('--slate-100'),
          200: withOpacity('--slate-200'),
          300: withOpacity('--slate-300'),
          400: withOpacity('--slate-400'),
          500: withOpacity('--slate-500'),
          600: withOpacity('--slate-600'),
          700: withOpacity('--slate-700'),
          800: withOpacity('--slate-800'),
          900: withOpacity('--slate-900'),
          950: withOpacity('--slate-950'),
        },
        blue: {
          50: withOpacity('--blue-50'),
          100: withOpacity('--blue-100'),
          200: withOpacity('--blue-200'),
          300: withOpacity('--blue-300'),
          400: withOpacity('--blue-400'),
          500: withOpacity('--blue-500'),
          600: withOpacity('--blue-600'),
          700: withOpacity('--blue-700'),
          800: withOpacity('--blue-800'),
          900: withOpacity('--blue-900'),
          950: withOpacity('--blue-950'),
        },
        emerald: {
          50: withOpacity('--emerald-50'),
          100: withOpacity('--emerald-100'),
          200: withOpacity('--emerald-200'),
          300: withOpacity('--emerald-300'),
          400: withOpacity('--emerald-400'),
          500: withOpacity('--emerald-500'),
          600: withOpacity('--emerald-600'),
          700: withOpacity('--emerald-700'),
          800: withOpacity('--emerald-800'),
          900: withOpacity('--emerald-900'),
          950: withOpacity('--emerald-950'),
        },
        amber: {
          50: withOpacity('--amber-50'),
          100: withOpacity('--amber-100'),
          200: withOpacity('--amber-200'),
          300: withOpacity('--amber-300'),
          400: withOpacity('--amber-400'),
          500: withOpacity('--amber-500'),
          600: withOpacity('--amber-600'),
          700: withOpacity('--amber-700'),
          800: withOpacity('--amber-800'),
          900: withOpacity('--amber-900'),
          950: withOpacity('--amber-950'),
        },
        indigo: {
          50: withOpacity('--indigo-50'),
          100: withOpacity('--indigo-100'),
          200: withOpacity('--indigo-200'),
          300: withOpacity('--indigo-300'),
          400: withOpacity('--indigo-400'),
          500: withOpacity('--indigo-500'),
          600: withOpacity('--indigo-600'),
          700: withOpacity('--indigo-700'),
          800: withOpacity('--indigo-800'),
          900: withOpacity('--indigo-900'),
          950: withOpacity('--indigo-950'),
        },
        purple: {
          50: withOpacity('--purple-50'),
          100: withOpacity('--purple-100'),
          200: withOpacity('--purple-200'),
          300: withOpacity('--purple-300'),
          400: withOpacity('--purple-400'),
          500: withOpacity('--purple-500'),
          600: withOpacity('--purple-600'),
          700: withOpacity('--purple-700'),
          800: withOpacity('--purple-800'),
          900: withOpacity('--purple-900'),
          950: withOpacity('--purple-950'),
        },
        rose: {
          50: withOpacity('--rose-50'),
          100: withOpacity('--rose-100'),
          200: withOpacity('--rose-200'),
          300: withOpacity('--rose-300'),
          400: withOpacity('--rose-400'),
          500: withOpacity('--rose-500'),
          600: withOpacity('--rose-600'),
          700: withOpacity('--rose-700'),
          800: withOpacity('--rose-800'),
          900: withOpacity('--rose-900'),
          950: withOpacity('--rose-950'),
        },
        red: {
          50: withOpacity('--red-50'),
          100: withOpacity('--red-100'),
          200: withOpacity('--red-200'),
          300: withOpacity('--red-300'),
          400: withOpacity('--red-400'),
          500: withOpacity('--red-500'),
          600: withOpacity('--red-600'),
          700: withOpacity('--red-700'),
          800: withOpacity('--red-800'),
          900: withOpacity('--red-900'),
          950: withOpacity('--red-950'),
        },
        sky: {
          50: withOpacity('--sky-50'),
          100: withOpacity('--sky-100'),
          200: withOpacity('--sky-200'),
          300: withOpacity('--sky-300'),
          400: withOpacity('--sky-400'),
          500: withOpacity('--sky-500'),
          600: withOpacity('--sky-600'),
          700: withOpacity('--sky-700'),
          800: withOpacity('--sky-800'),
          900: withOpacity('--sky-900'),
          950: withOpacity('--sky-950'),
        },
        teal: {
          50: withOpacity('--teal-50'),
          100: withOpacity('--teal-100'),
          200: withOpacity('--teal-200'),
          300: withOpacity('--teal-300'),
          400: withOpacity('--teal-400'),
          500: withOpacity('--teal-500'),
          600: withOpacity('--teal-600'),
          700: withOpacity('--teal-700'),
          800: withOpacity('--teal-800'),
          900: withOpacity('--teal-900'),
          950: withOpacity('--teal-950'),
        },
        white: withOpacity('--white'),
        black: withOpacity('--black'),
        brand: {
          DEFAULT: 'var(--brand)',
          strong: 'var(--brand-strong)',
          soft: 'var(--brand-soft)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          strong: 'var(--secondary-strong)',
          soft: 'var(--secondary-soft)',
        },
        success: {
          DEFAULT: 'var(--success)',
          strong: 'var(--success-strong)',
          soft: 'var(--success-soft)',
          line: 'var(--success-line)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          strong: 'var(--warning-strong)',
          soft: 'var(--warning-soft)',
          line: 'var(--warning-line)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          strong: 'var(--danger-strong)',
          soft: 'var(--danger-soft)',
          line: 'var(--danger-line)',
        },
        ink: {
          DEFAULT: 'var(--text-strong)',
          soft: 'var(--text-soft)',
        },
        muted: 'var(--muted)',
        highlight: 'var(--highlight)',
        surface: {
          DEFAULT: 'var(--surface)',
          strong: 'var(--surface-strong)',
          white: 'var(--surface-white)',
        },
      },
    },
  },
  plugins: [],
};
