// Tenant-toggleable feature keys, mapped to the nav label translation key.
// Kept separate from routes.js to avoid a circular import with pages
// (e.g. PlatformAdminPage) that need this list but are also referenced by routes.js.
export const TENANT_FEATURE_ROUTES = [
  { feature: 'products', labelKey: 'nav.products' },
  { feature: 'dsrs', labelKey: 'nav.dsrs' },
  { feature: 'customers', labelKey: 'nav.customers' },
  { feature: 'morning-issue', labelKey: 'nav.morningIssue' },
  { feature: 'settlements', labelKey: 'nav.eveningSettlement' },
  { feature: 'reports', labelKey: 'nav.reports' },
  { feature: 'history', labelKey: 'nav.history' },
  { feature: 'expenses', labelKey: 'nav.expenses' },
  { feature: 'dsr-finance', labelKey: 'nav.dsrFinance' },
  { feature: 'profit', labelKey: 'nav.profit' },
  { feature: 'activity-logs', labelKey: 'nav.activityLogs' },
  { feature: 'trash', labelKey: 'nav.trash' },
  { feature: 'suppliers', labelKey: 'nav.suppliers' },
  { feature: 'purchase-receive', labelKey: 'nav.purchaseReceive' },
  { feature: 'supplier-payments', labelKey: 'nav.supplierPayments' },
  { feature: 'supplier-statement', labelKey: 'nav.supplierStatement' },
  { feature: 'retailer-quick-sale', labelKey: 'nav.retailerQuickSale' },
  { feature: 'retailer-sales-invoices', labelKey: 'nav.retailerSalesInvoices' },
  { feature: 'retailer-promotions', labelKey: 'nav.retailerPromotions' },
  { feature: 'retailer-customer-due', labelKey: 'nav.retailerCustomerDue' },
  { feature: 'retailer-due-collection', labelKey: 'nav.retailerDueCollection' },
  { feature: 'retailer-sales-return', labelKey: 'nav.retailerSalesReturn' },
  { feature: 'retailer-daily-sales-report', labelKey: 'nav.retailerDailySalesReport' },
  { feature: 'retailer-profit-report', labelKey: 'nav.retailerProfitReport' },
  { feature: 'finance-dashboard', labelKey: 'nav.financeDashboard' },
  { feature: 'finance-accounts', labelKey: 'nav.financeAccounts' },
  { feature: 'dashboard', labelKey: 'nav.dashboard' },
  { feature: 'my-profile', labelKey: 'nav.profile' },
  { feature: 'security', labelKey: 'nav.security' },
  { feature: 'help-desk', labelKey: 'nav.helpDesk' },
  { feature: 'org-settings', labelKey: 'nav.orgSettings' },
  { feature: 'user-management', labelKey: 'nav.users' },
  { feature: 'permissions', labelKey: 'nav.permissions' },
  { feature: 'retail-customers', labelKey: 'nav.retailCustomers' },
  { feature: 'retail-customer-retention', labelKey: 'nav.retailCustomerRetention' },
  { feature: 'database-backup', labelKey: 'nav.databaseBackup' },
  { feature: 'platform', labelKey: 'nav.platform' },
  { feature: 'visitor-chats', labelKey: 'nav.visitorChats' },
  { feature: 'system-health', labelKey: 'nav.systemHealth' },
  { feature: 'error-logs', labelKey: 'nav.errorLogs' },
  { feature: 'damaged-stock', labelKey: 'nav.damagedStock' },
  { feature: 'stock-movement', labelKey: 'nav.stockMovement' },
  { feature: 'low-stock-alerts', labelKey: 'nav.lowStockAlerts' },
];
