version = 0.1

[default.deploy.parameters]
stack_name   = "stockledger-api"
region       = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3   = true

parameter_overrides = [
  "DatabaseUrl=postgresql://postgres.loqhcqibtbuopjchenam:s1PcUrahMBgQ72TE@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=no-verify&pgbouncer=true&connection_limit=1&schema=public",
  "SessionCookieName=arinda_session",
  "SessionDays=7",
]
