export const PUBLIC_ROUTES = [
  '/',
  '/landing',
  '/features',
  '/features/inventory-management',
  '/features/retail-pos',
  '/features/accounting',
  '/features/hr-payroll',
  '/features/purchase-management',
  '/features/due-collection',
  '/features/dsr-dealer-management',
  '/features/installment-sales',
  '/features/reporting',
  '/features/repair-warranty',
  '/solutions',
  '/solutions/retail-shop',
  '/solutions/wholesale-business',
  '/solutions/dealer-distributor',
  '/solutions/dsr-sales-team',
  '/solutions/pharmacy',
  '/solutions/grocery-store',
  '/pricing',
  '/contact',
  '/get-started',
  '/founder',
  '/privacy-policy',
  '/terms',
];

export const INDEXABLE_PUBLIC_ROUTES = PUBLIC_ROUTES.filter((route) => route !== '/');
