export const AUDIT_MODULES = [
  "products",
  "dsrs",
  "customers",
  "expenses",
  "morning-issue",
  "settlements",
  "dsr-finance",
  "due-ledger",
  "users",
  "suppliers",
  "purchases",
  "retailer",
  "support",
  "hr",
  "system",
];

const ENTITY_TYPE_MODULES = {
  product: "products",
  category: "products",
  dsr: "dsrs",
  dsr_target: "dsrs",
  customer: "customers",
  expense: "expenses",
  issue: "morning-issue",
  settlement: "settlements",
  due_ledger: "due-ledger",
  user: "users",
  supplier: "suppliers",
  supplier_due_ledger: "suppliers",
  purchase_receipt: "purchases",
  supplier_payment: "purchases",
  sales_invoice: "retailer",
  sales_return: "retailer",
  customer_payment: "retailer",
  customer_due_ledger: "retailer",
  quotation: "retailer",
  trade_in: "retailer",
  retail_customer: "retailer",
  retail_promotion: "retailer",
  help_desk_ticket: "support",
  contact_message: "support",
  department: "hr",
  designation: "hr",
  employee: "hr",
  salary_payment: "hr",
  tenant: "system",
  upload: "system",
};

export function moduleForEntityType(entityType) {
  return ENTITY_TYPE_MODULES[entityType] || "system";
}

