export const CUSTOMER_DUE_LEDGER_TYPES = {
  OPENING: "OPENING",
  SALE_DUE: "SALE_DUE",
  COLLECTION: "COLLECTION",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
  RETURN_ADJUSTMENT: "RETURN_ADJUSTMENT",
};

export const CUSTOMER_DUE_LEDGER_TYPE_VALUES = Object.values(CUSTOMER_DUE_LEDGER_TYPES);
