export const DSR_DUE_LEDGER_TYPES = {
  OPENING: "OPENING",
  SALE_DUE: "SALE_DUE",
  COLLECTION: "COLLECTION",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
};

export const DSR_DUE_LEDGER_TYPE_VALUES = Object.values(DSR_DUE_LEDGER_TYPES);
