// Feature keys correspond to APP_ROUTES ids in the frontend that can be
// individually enabled/disabled per tenant by a platform admin.
export const TENANT_FEATURES = [
  "products",
  "dsrs",
  "customers",
  "morning-issue",
  "settlements",
  "reports",
  "history",
  "expenses",
  "dsr-finance",
  "profit",
  "activity-logs",
  "trash",
  "suppliers",
  "purchase-receive",
  "supplier-payments",
  "supplier-statement",
  "retailer-quick-sale",
  "retailer-sales-invoices",
  "retailer-promotions",
  "retailer-customer-due",
  "retailer-due-collection",
  "retailer-sales-return",
  "retailer-daily-sales-report",
  "retailer-profit-report",
  "finance-accounts",
  "finance-dashboard",
];
