import { USER_ROLES } from "./roles.js";
import { getCachedPermissions } from "./permissionCache.js";

export const PERMISSIONS = {
  VIEW_STATE: "view_state",
  MANAGE_PRODUCTS: "manage_products",
  MANAGE_DSRS: "manage_dsrs",
  MANAGE_CUSTOMERS: "manage_customers",
  CREATE_ISSUES: "create_issues",
  UPDATE_ISSUES: "update_issues",
  CREATE_SETTLEMENTS: "create_settlements",
  UPDATE_SETTLEMENTS: "update_settlements",
  MANAGE_EXPENSES: "manage_expenses",
  MANAGE_DSR_FINANCE: "manage_dsr_finance",
  VIEW_ACTIVITY_LOGS: "view_activity_logs",
  MANAGE_USERS: "manage_users",
  MANAGE_BACKUPS: "manage_backups",
  MANAGE_ORG: "manage_org",
  MANAGE_TENANTS: "manage_tenants",
};

export const TENANT_BUSINESS_PERMISSIONS = [
  PERMISSIONS.VIEW_STATE,
  PERMISSIONS.MANAGE_PRODUCTS,
  PERMISSIONS.MANAGE_DSRS,
  PERMISSIONS.MANAGE_CUSTOMERS,
  PERMISSIONS.CREATE_ISSUES,
  PERMISSIONS.UPDATE_ISSUES,
  PERMISSIONS.CREATE_SETTLEMENTS,
  PERMISSIONS.UPDATE_SETTLEMENTS,
  PERMISSIONS.MANAGE_EXPENSES,
  PERMISSIONS.MANAGE_DSR_FINANCE,
  PERMISSIONS.VIEW_ACTIVITY_LOGS,
  PERMISSIONS.MANAGE_USERS,
  PERMISSIONS.MANAGE_BACKUPS,
  PERMISSIONS.MANAGE_ORG,
];

export const ROLE_PERMISSIONS = {
  [USER_ROLES.PLATFORM_ADMIN]: [...Object.values(PERMISSIONS)],
  [USER_ROLES.SYSTEM_DEVELOPER]: [...Object.values(PERMISSIONS)],
  [USER_ROLES.SUPER_ADMIN]: TENANT_BUSINESS_PERMISSIONS,
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.VIEW_STATE,
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_DSRS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.CREATE_ISSUES,
    PERMISSIONS.UPDATE_ISSUES,
    PERMISSIONS.CREATE_SETTLEMENTS,
    PERMISSIONS.UPDATE_SETTLEMENTS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.MANAGE_DSR_FINANCE,
    PERMISSIONS.VIEW_ACTIVITY_LOGS,
  ],
  [USER_ROLES.MANAGER]: [
    PERMISSIONS.VIEW_STATE,
    PERMISSIONS.CREATE_ISSUES,
    PERMISSIONS.UPDATE_ISSUES,
    PERMISSIONS.CREATE_SETTLEMENTS,
    PERMISSIONS.UPDATE_SETTLEMENTS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.MANAGE_DSR_FINANCE,
    PERMISSIONS.VIEW_ACTIVITY_LOGS,
  ],
  [USER_ROLES.OPERATOR]: [PERMISSIONS.VIEW_STATE, PERMISSIONS.CREATE_ISSUES, PERMISSIONS.CREATE_SETTLEMENTS],
};

export function getRolePermissions(role, tenantId) {
  if (role === USER_ROLES.SYSTEM_DEVELOPER || role === USER_ROLES.PLATFORM_ADMIN) {
    return ROLE_PERMISSIONS[role] || [];
  }

  return getCachedPermissions(role, tenantId) || ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(role, permission, tenantId) {
  if (role === USER_ROLES.SYSTEM_DEVELOPER) {
    return true;
  }

  return getRolePermissions(role, tenantId).includes(permission);
}
