export const PRODUCT_SERIAL_STATUSES = {
  IN_STOCK: "IN_STOCK",
  SOLD: "SOLD",
  RETURNED: "RETURNED",
  DAMAGED: "DAMAGED",
  WARRANTY: "WARRANTY",
  DELETED: "DELETED",
};

export const PRODUCT_SERIAL_STATUS_VALUES = Object.values(PRODUCT_SERIAL_STATUSES);
