export const QUOTATION_STATUSES = {
  DRAFT: "DRAFT",
  SENT: "SENT",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  CONVERTED: "CONVERTED",
};

export const QUOTATION_STATUS_VALUES = Object.values(QUOTATION_STATUSES);

// Statuses that can transition to CONVERTED
export const QUOTATION_CONVERTIBLE_STATUSES = [
  QUOTATION_STATUSES.DRAFT,
  QUOTATION_STATUSES.SENT,
  QUOTATION_STATUSES.ACCEPTED,
];

// Statuses where the quotation is no longer editable
export const QUOTATION_CLOSED_STATUSES = [
  QUOTATION_STATUSES.REJECTED,
  QUOTATION_STATUSES.CONVERTED,
];
