export const SR_DUE_LEDGER_TYPES = {
  OPENING: "OPENING",
  HANDOVER: "HANDOVER",
  COLLECTION: "COLLECTION",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
};

export const SR_DUE_LEDGER_TYPE_VALUES = Object.values(SR_DUE_LEDGER_TYPES);
