export const STOCK_MOVEMENT_TYPES = {
  OPENING: "OPENING",
  MORNING_ISSUE: "MORNING_ISSUE",
  SETTLEMENT_RETURN: "SETTLEMENT_RETURN",
  DAMAGE: "DAMAGE",
  EXTRA_RETURN: "EXTRA_RETURN",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
};

export const STOCK_MOVEMENT_TYPE_VALUES = Object.values(STOCK_MOVEMENT_TYPES);
