export const STOCK_MOVEMENT_TYPES = {
  OPENING: "OPENING",
  MORNING_ISSUE: "MORNING_ISSUE",
  SETTLEMENT_RETURN: "SETTLEMENT_RETURN",
  DAMAGE: "DAMAGE",
  EXTRA_RETURN: "EXTRA_RETURN",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
  DAMAGE_CLEAR: "DAMAGE_CLEAR",
  PURCHASE_RECEIVE: "PURCHASE_RECEIVE",
  PURCHASE_RETURN: "PURCHASE_RETURN",
  SALE: "SALE",
  SALES_RETURN: "SALES_RETURN",
  TRADE_IN_RECEIVED: "TRADE_IN_RECEIVED",
  TRADE_IN_SALE: "TRADE_IN_SALE",
};

export const STOCK_MOVEMENT_TYPE_VALUES = Object.values(STOCK_MOVEMENT_TYPES);
