export const SUPPLIER_DUE_LEDGER_TYPES = {
  OPENING: "OPENING",
  PURCHASE_DUE: "PURCHASE_DUE",
  PAYMENT: "PAYMENT",
  DISCOUNT: "DISCOUNT",
  RETURN: "RETURN",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
  PROMOTION_CREDIT: "PROMOTION_CREDIT",
};

export const SUPPLIER_DUE_LEDGER_TYPE_VALUES = Object.values(SUPPLIER_DUE_LEDGER_TYPES);
