export const SUPPLIER_DUE_LEDGER_TYPES = {
  OPENING: "OPENING",
  PURCHASE_DUE: "PURCHASE_DUE",
  PAYMENT: "PAYMENT",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
};

export const SUPPLIER_DUE_LEDGER_TYPE_VALUES = Object.values(SUPPLIER_DUE_LEDGER_TYPES);
