export const TRADE_IN_CONDITIONS = {
  EXCELLENT: "EXCELLENT",
  GOOD: "GOOD",
  FAIR: "FAIR",
  POOR: "POOR",
  DAMAGED: "DAMAGED",
};

export const TRADE_IN_CONDITION_VALUES = Object.values(TRADE_IN_CONDITIONS);

export const PAYMENT_METHODS = ["CASH", "CARD", "MOBILE_BANKING", "BANK_TRANSFER", "CREDIT"];
