export const WARRANTY_CLAIM_STATUSES = {
  RECEIVED: "RECEIVED",
  SENT_TO_SUPPLIER: "SENT_TO_SUPPLIER",
  REPAIRED: "REPAIRED",
  REPLACED: "REPLACED",
  REJECTED: "REJECTED",
  DELIVERED: "DELIVERED",
};

export const WARRANTY_CLAIM_STATUS_VALUES = Object.values(WARRANTY_CLAIM_STATUSES);

// Claims stop being actionable once delivered back to the customer or rejected outright.
export const WARRANTY_CLAIM_CLOSED_STATUSES = [
  WARRANTY_CLAIM_STATUSES.DELIVERED,
  WARRANTY_CLAIM_STATUSES.REJECTED,
];
